version: "3.8"

services:
  portfolio-server:
    container_name: portfolio-server
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5002:5002"
    restart: always
    env_file:
      - .env
