export const skillIcons: any = {
  html: "FaHtml5",
  css: "FaCss3Alt",
  "tailwind css": "FaTailwind",
  bootstrap: "FaBootstrap",
  javascript: "FaJsSquare",
  typescript: "FaReact",
  reactjs: "FaReact",
  redux: "FaRedux",
  nextjs: "TbBrandNextjs",
  "rest api": "FaServer",
  nodejs: "FaNodeJs",
  expressjs: "FaNodeJs",
  nestjs: "SiNestjs",
  "prisma orm": "FaDatabase",
  rypeorm: "FaDatabase",
  mongoose: "FaDatabase",
  mongodb: "FaDatabase",
  mysql: "FaDatabase",
  postgresql: "FaDatabase",
  docker: "FaDocker",
  aws: "FaAws",
  redis: "FaDatabase",
  rabbitmq: "FaDatabase",
  "apache kafka": "FaDatabase",
  "socket.io": "FaComments",
  "website authentication": "FaLock",
  "mvc and modular architecture": "FaProjectDiagram",
  microservice: "FaSitemap",
  "system design": "FaSitemap",
};
