export const blogs = [
  {
    id: "1",
    title: "The Power of Asynchronous JavaScript",
    type: "tips",
    image: "https://i.ibb.co/GVh4H29/The-Power-of-Asynchronous-Java-Script.png",
    body: "In the world of JavaScript, asynchronous programming plays a crucial role in improving performance and user experience. By leveraging asynchronous functions and callbacks, developers can execute non-blocking code, allowing multiple operations to run concurrently without waiting for each other to finish. This blog explores the fundamentals of asynchronous JavaScript and how it empowers developers to build responsive and efficient web applications.",
    createdAt: new Date(),
    comments: 3,
  },
  {
    id: "2",
    title: "Mastering CSS Flexbox",
    type: "tutorial",
    image: "https://i.ibb.co/dptCMgq/Mastering-CSS-Flexbox.png",
    body: "<p>Flexbox is a powerful layout model that enables developers to design flexible and responsive web layouts with ease.</p> <p> From creating complex grid structures to aligning and distributing content, mastering CSS Flexbox opens up a world of possibilities in web design.</p>  <p>This blog provides a comprehensive guide to understanding and implementing Flexbox techniques for creating modern and dynamic web layouts.</p>",
    createdAt: new Date(),
    comments: 0,
  },
  {
    id: "3",
    title: "Getting Started with React Hooks",
    type: "tutorial",
    image: "https://i.ibb.co/rtY1Wds/Getting-Started-with-React-Hooks.png",
    body: "React Hooks revolutionized the way developers build React applications by introducing a simpler and more intuitive way to manage state and side effects. With Hooks like useState and useEffect, developers can leverage functional components to write cleaner and more maintainable code. This blog offers a beginner-friendly introduction to React Hooks and demonstrates how to use them to enhance your React projects.",
    createdAt: new Date(),
    comments: 1,
  },
  {
    id: "4",
    title: "Exploring the World of Node.js",
    type: "tutorial",
    image: "",
    body: "Node.js has emerged as a popular runtime environment for building scalable and efficient server-side applications. With its event-driven architecture and non-blocking I/O operations, Node.js enables developers to create high-performance web servers and APIs. This blog delves into the core concepts of Node.js and provides insights into its key features and capabilities.",
    createdAt: new Date(),
    comments: 5,
  },
  {
    id: "5",
    title: "The Art of Responsive Web Design",
    type: "tutorial",
    image: "https://i.ibb.co/ChRvS7D/The-Art-of-Responsive-Web-Design.png",
    body: "Responsive web design is essential for ensuring optimal user experience across various devices and screen sizes. By employing fluid grids, flexible images, and media queries, developers can create websites that adapt seamlessly to desktops, tablets, and smartphones. This blog explores the principles and best practices of responsive web design, equipping developers with the knowledge to create visually stunning and user-friendly websites.",
    createdAt: new Date(),
    comments: 0,
  },
];
