const designationRoles: string[] = [
  "Full Stack Developer",
  "MERN Stack Developer",
  "Frontend Developer",
  "Backend Developer",
  "Microservices Developer",
  "Software Engineer",
  "NestJS Developer",
  "ReactJS Developer",
  "Next.js Developer",
  "API Integration Specialist",
  "TypeScript Developer",
  "JavaScript Developer",
  "Web Application Developer",
  "DevOps Engineer",
  "Cloud Engineer (AWS)",
  "Database Developer",
  "System Design Engineer",
  "Solution Architect",
  "Technical Lead",
  "Redis/RabbitMQ Engineer",
  "Authentication & Security Engineer",
  "Firebase Developer",
  "MVC/Design Pattern Engineer",
];
export default designationRoles;
