const tagOptions = [
  "Tutorial",
  "Tips",
  "Web Development",
  "Lifestyle",
  "Travel",
  "Health",
  "Fitness",
  "Finance",
  "Personal Development",
  "Productivity",
  "Technology",
  "Programming",
  "Career Advice",
  "Education",
  "Marketing",
  "SEO",
  "Design",
  "UI/UX",
  "Photography",
  "Food",
  "Recipes",
  "Parenting",
  "Relationships",
  "Fashion",
  "Beauty",
  "Entertainment",
  "Gaming",
  "Books",
  "Art",
  "Culture",
  "Business",
  "Startups",
  "News",
  "Politics",
  "Science",
  "Psychology",
  "Spirituality",
  "Self Improvement",
  "Pets",
  "DIY",
  "Crafts",
  "Automotive",
  "Real Estate",
  "Cryptocurrency",
  "Investing",
  "Sustainability",
  "AI",
  "Machine Learning",
  "Data Science",
  "DevOps",
  "Cloud Computing",
  "Cybersecurity",
  "Remote Work",
  "Freelancing",
  "Side Hustles",
  "E-Commerce",
  "UI Design",
  "Backend",
  "Frontend",
  "APIs",
  "Databases",
  "NoSQL",
  "SQL",
  "Open Source",
  "Software Engineering",
  "Mobile Development",
  "React",
  "Vue",
  "Angular",
  "Next.js",
  "Node.js",
  "NestJS",
  "Express.js",
  "GraphQL",
  "REST",
  "Testing",
  "Unit Testing",
  "Integration Testing",
  "Agile",
  "Scrum",
  "Project Management",
  "Time Management",
  "Mindfulness",
  "Habits",
  "Motivation",
  "Inspiration",
  "Ethics",
  "Philosophy",
  "Product Design",
  "Branding",
  "Typography",
  "Color Theory",
  "UX Research",
  "Usability",
  "Prototyping",
  "Animations",
  "Motion Design",
  "Storytelling",
  "Content Creation",
  "Writing",
  "Blogging",
  "Video Editing",
  "Podcasts",
  "Streaming",
  "Music",
  "Film",
  "Photography Tips",
  "Fitness Tips",
  "Nutrition",
  "Mental Health",
];
export default tagOptions;
